/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop_project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author AMAL
 */
public class Admin extends javax.swing.JFrame {

   
     Connection con=null;

    public Admin() {
        initComponents();
       
         try 
        {
    
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/hope?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC" , 
            "root", "1234");
        }
        catch ( java.sql.SQLException sqlException ) 
        {
            System.out.println(sqlException.getMessage() );
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Right = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        HospitalName = new javax.swing.JLabel();
        Hospital = new javax.swing.JLabel();
        Left = new javax.swing.JPanel();
        Login = new javax.swing.JLabel();
        UserName = new javax.swing.JLabel();
        User_text = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        Pass_text = new javax.swing.JPasswordField();
        Loginbt = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Login_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 700));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 750));
        jPanel1.setLayout(null);

        Right.setBackground(new java.awt.Color(3, 28, 54));
        Right.setPreferredSize(new java.awt.Dimension(650, 750));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Hospital.png"))); // NOI18N

        HospitalName.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        HospitalName.setForeground(new java.awt.Color(255, 255, 255));
        HospitalName.setText("Hope Hospital");

        Hospital.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        Hospital.setForeground(new java.awt.Color(255, 255, 255));
        Hospital.setText("Your Health, Our Priority");

        javax.swing.GroupLayout RightLayout = new javax.swing.GroupLayout(Right);
        Right.setLayout(RightLayout);
        RightLayout.setHorizontalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightLayout.createSequentialGroup()
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RightLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(HospitalName))
                    .addGroup(RightLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(Logo))
                    .addGroup(RightLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(Hospital)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        RightLayout.setVerticalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(HospitalName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Hospital)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        jPanel1.add(Right);
        Right.setBounds(0, 0, 650, 750);

        Left.setBackground(new java.awt.Color(255, 255, 255));
        Left.setPreferredSize(new java.awt.Dimension(650, 750));

        Login.setBackground(new java.awt.Color(3, 28, 54));
        Login.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        Login.setForeground(new java.awt.Color(3, 28, 54));
        Login.setText("LOGIN AS ADMIN");

        UserName.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        UserName.setText("UserName");

        User_text.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        User_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User_textActionPerformed(evt);
            }
        });

        Password.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        Password.setText("Password");

        Pass_text.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Pass_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pass_textActionPerformed(evt);
            }
        });

        Loginbt.setBackground(new java.awt.Color(3, 28, 54));
        Loginbt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Loginbt.setForeground(new java.awt.Color(255, 255, 255));
        Loginbt.setText("Login");
        Loginbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginbtActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(3, 28, 54));
        jLabel5.setText("Or want to continue as user ?");

        Login_btn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Login_btn.setForeground(new java.awt.Color(204, 0, 102));
        Login_btn.setText("Login");
        Login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LeftLayout = new javax.swing.GroupLayout(Left);
        Left.setLayout(LeftLayout);
        LeftLayout.setHorizontalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftLayout.createSequentialGroup()
                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LeftLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(Login))
                    .addGroup(LeftLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LeftLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Login_btn))
                            .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Pass_text, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                                .addComponent(UserName)
                                .addComponent(Password)
                                .addComponent(Loginbt, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(User_text)))))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        LeftLayout.setVerticalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(Login)
                .addGap(50, 50, 50)
                .addComponent(UserName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(User_text, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pass_text, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(Loginbt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Login_btn))
                .addContainerGap(243, Short.MAX_VALUE))
        );

        jPanel1.add(Left);
        Left.setBounds(650, 0, 660, 750);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void User_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_User_textActionPerformed

    private void Pass_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pass_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pass_textActionPerformed

    private void LoginbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginbtActionPerformed
                                         
    String username = User_text.getText().trim(); // Trim whitespace
    String password = new String(Pass_text.getPassword());

    // Check if fields are empty
    if (username.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Username or Password cannot be empty!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // SQL query to validate admin credentials
    String adminQuery = "SELECT * FROM admins WHERE username = ? AND password = ?"; // Directly check admin

    try {
        if (con != null) { // Ensure connection is not null
            PreparedStatement ps = con.prepareStatement(adminQuery);
            ps.setString(1, username);
            ps.setString(2, password); // Check password directly
            ResultSet rs = ps.executeQuery();

            if (rs.next()) { // Admin credentials are correct
                JOptionPane.showMessageDialog(this, "Login Successful! Welcome Admin!", "Success", JOptionPane.INFORMATION_MESSAGE);
                
                // Open the admin view
                View ViewFrame = new View();
                ViewFrame.setVisible(true);
                ViewFrame.pack(); // Adjust the frame size based on its components
                ViewFrame.setLocationRelativeTo(null); // Centers the frame on the screen
            } else {
                // Incorrect username or password
                JOptionPane.showMessageDialog(this, "Incorrect Username or Password!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Database connection is not established!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (SQLException e) {
        e.printStackTrace(); // Print the stack trace for debugging
        JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_LoginbtActionPerformed

    private void Login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_btnActionPerformed

        Login LoginFrame = new Login();
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_Login_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Hospital;
    private javax.swing.JLabel HospitalName;
    private javax.swing.JPanel Left;
    private javax.swing.JLabel Login;
    private javax.swing.JButton Login_btn;
    private javax.swing.JButton Loginbt;
    private javax.swing.JLabel Logo;
    private javax.swing.JPasswordField Pass_text;
    private javax.swing.JLabel Password;
    private javax.swing.JPanel Right;
    private javax.swing.JLabel UserName;
    private javax.swing.JTextField User_text;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
