/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop_project;

/**
 *
 * @author AMAL
 */
public class Doctors extends javax.swing.JFrame {

    /**
     * Creates new form Doctors
     */
    public Doctors() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Logout = new javax.swing.JButton();
        Hope_Label = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Services1 = new javax.swing.JButton();
        AboutUs = new javax.swing.JButton();
        Doctors = new javax.swing.JButton();
        Services = new javax.swing.JButton();
        Logout1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 700));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 700));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(3, 28, 54));

        Logout.setBackground(new java.awt.Color(3, 28, 54));
        Logout.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        Hope_Label.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        Hope_Label.setForeground(new java.awt.Color(255, 255, 255));
        Hope_Label.setText("HopeHospital");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/hop1.png"))); // NOI18N

        Services1.setBackground(new java.awt.Color(3, 28, 54));
        Services1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Services1.setForeground(new java.awt.Color(255, 255, 255));
        Services1.setText("View Doctors");
        Services1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Services1ActionPerformed(evt);
            }
        });

        AboutUs.setBackground(new java.awt.Color(3, 28, 54));
        AboutUs.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        AboutUs.setForeground(new java.awt.Color(255, 255, 255));
        AboutUs.setText("About Us");
        AboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutUsActionPerformed(evt);
            }
        });

        Doctors.setBackground(new java.awt.Color(3, 28, 54));
        Doctors.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Doctors.setForeground(new java.awt.Color(255, 255, 255));
        Doctors.setText("Our Doctors");
        Doctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorsActionPerformed(evt);
            }
        });

        Services.setBackground(new java.awt.Color(3, 28, 54));
        Services.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Services.setForeground(new java.awt.Color(255, 255, 255));
        Services.setText("Patient Services");
        Services.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServicesActionPerformed(evt);
            }
        });

        Logout1.setBackground(new java.awt.Color(3, 28, 54));
        Logout1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Logout1.setForeground(new java.awt.Color(255, 255, 255));
        Logout1.setText("Return");
        Logout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Hope_Label)
                .addGap(145, 145, 145)
                .addComponent(AboutUs)
                .addGap(18, 18, 18)
                .addComponent(Doctors)
                .addGap(18, 18, 18)
                .addComponent(Services)
                .addGap(18, 18, 18)
                .addComponent(Services1)
                .addGap(102, 102, 102)
                .addComponent(Logout1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Logout)
                .addGap(565, 565, 565))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Services1)
                            .addComponent(Logout)
                            .addComponent(AboutUs)
                            .addComponent(Doctors)
                            .addComponent(Services)
                            .addComponent(Logout1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Hope_Label)
                            .addComponent(jLabel2))))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1858, 60);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(3, 28, 54));
        jLabel1.setText("Our Best Doctors");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(466, 62, 357, 56);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/drd.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(100, 210, 154, 210);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(3, 28, 54));
        jLabel5.setText("Dr. Afaf Naji");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(130, 430, 79, 17);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(3, 28, 54));
        jLabel6.setText("Dental");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(150, 450, 50, 17);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(3, 28, 54));
        jLabel7.setText("Orthodontics Specialist");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(110, 470, 131, 17);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/dro1.png"))); // NOI18N
        jLabel8.setPreferredSize(new java.awt.Dimension(154, 210));
        jLabel8.setRequestFocusEnabled(false);
        jPanel1.add(jLabel8);
        jLabel8.setBounds(380, 210, 167, 210);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(3, 28, 54));
        jLabel9.setText("Dr. Sari Soukarieh");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(400, 430, 117, 17);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(3, 28, 54));
        jLabel10.setText("Ophthalmology");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(410, 450, 86, 17);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(3, 28, 54));
        jLabel11.setText("Ophthalmology Specialist");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(390, 470, 143, 17);

        jButton2.setBackground(new java.awt.Color(3, 28, 54));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Book Appointment");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(80, 500, 180, 27);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/drc1.png"))); // NOI18N
        jLabel12.setPreferredSize(new java.awt.Dimension(154, 210));
        jLabel12.setRequestFocusEnabled(false);
        jPanel1.add(jLabel12);
        jLabel12.setBounds(720, 210, 167, 210);

        jButton3.setBackground(new java.awt.Color(3, 28, 54));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Book Appointment");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(370, 500, 180, 27);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(3, 28, 54));
        jLabel13.setText("Dr. Hisham Khalil");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(750, 430, 112, 17);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(3, 28, 54));
        jLabel14.setText("Consultant Interventional Cardiology");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(700, 470, 206, 17);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(3, 28, 54));
        jLabel15.setText("Cardiology");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(770, 450, 70, 17);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/drm.png"))); // NOI18N
        jLabel16.setPreferredSize(new java.awt.Dimension(154, 210));
        jLabel16.setRequestFocusEnabled(false);
        jPanel1.add(jLabel16);
        jLabel16.setBounds(1030, 210, 167, 210);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(3, 28, 54));
        jLabel17.setText("Dr. Basmah Aldhafer");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(1060, 430, 131, 17);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(3, 28, 54));
        jLabel18.setText("Orthopedic");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(1090, 450, 63, 17);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(3, 28, 54));
        jLabel19.setText("hand surgery");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(1090, 470, 74, 17);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 32)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(3, 28, 54));
        jLabel3.setText("We Take Care Of Your Health");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(455, 124, 389, 38);

        jButton4.setBackground(new java.awt.Color(3, 28, 54));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Book Appointment");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(710, 500, 180, 27);

        jButton1.setBackground(new java.awt.Color(3, 28, 54));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Book Appointment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1030, 500, 180, 27);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
          // Show a friendly confirmation message to the patient
        javax.swing.JOptionPane.showMessageDialog(null,
            "Visit us again. Take care of yourself!",
            "Logout",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);

        // Open the Login frame
        Login LoginFrame = new Login();
        LoginFrame.setVisible(true);
        LoginFrame.pack(); // Adjusts the frame size based on its components
        LoginFrame.setLocationRelativeTo(null); // Centers the frame on the screen

        // Close the current frame
        this.dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    private void Services1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Services1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Services1ActionPerformed

    private void AboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutUsActionPerformed
        // TODO add your handling code here:
          // TODO add your handling code here:
         About AboutFrame = new About();
         AboutFrame.setVisible(true);
         AboutFrame.pack();// This adjusts the frame size based on its components
         AboutFrame.setLocationRelativeTo(null); // Centers the frame on the screen
    }//GEN-LAST:event_AboutUsActionPerformed

    private void DoctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorsActionPerformed

    private void ServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServicesActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
         Services ServicesFrame = new Services();
         ServicesFrame.setVisible(true);
         ServicesFrame.pack();// This adjusts the frame size based on its components
         ServicesFrame.setLocationRelativeTo(null); // Centers the frame on the screen
    }//GEN-LAST:event_ServicesActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        // TODO add your handling code here:
        Book BookFrame = new Book();
         BookFrame.setVisible(true);
         BookFrame.pack();// This adjusts the frame size based on its components
         BookFrame.setLocationRelativeTo(null); // Centers the frame on the screen
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        // TODO add your handling code here:
        Book BookFrame = new Book();
         BookFrame.setVisible(true);
         BookFrame.pack();// This adjusts the frame size based on its components
         BookFrame.setLocationRelativeTo(null); // Centers the frame on the screen
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        // TODO add your handling code here:
        Book BookFrame = new Book();
         BookFrame.setVisible(true);
         BookFrame.pack();// This adjusts the frame size based on its components
         BookFrame.setLocationRelativeTo(null); // Centers the frame on the screen
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        // TODO add your handling code here:
        Book BookFrame = new Book();
         BookFrame.setVisible(true);
         BookFrame.pack();// This adjusts the frame size based on its components
         BookFrame.setLocationRelativeTo(null); // Centers the frame on the screen
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Logout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout1ActionPerformed
        // TODO add your handling code here:
           // TODO add your handling code here:
        HomePage HomeFrame = new HomePage();
            HomeFrame.setVisible(true);
            HomeFrame.pack();
            HomeFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_Logout1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctors().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutUs;
    private javax.swing.JButton Doctors;
    private javax.swing.JLabel Hope_Label;
    private javax.swing.JButton Logout;
    private javax.swing.JButton Logout1;
    private javax.swing.JButton Services;
    private javax.swing.JButton Services1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
