/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop_project;

/**
 *
 * @author AMAL
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Doctors = new javax.swing.JButton();
        Services = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        Hope_Label = new javax.swing.JLabel();
        AboutUs = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ContactUs = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        serv = new javax.swing.JButton();
        book = new javax.swing.JButton();
        contactbtn = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 700));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(3, 28, 54));

        Doctors.setBackground(new java.awt.Color(3, 28, 54));
        Doctors.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Doctors.setForeground(new java.awt.Color(255, 255, 255));
        Doctors.setText("Our Doctors");
        Doctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorsActionPerformed(evt);
            }
        });

        Services.setBackground(new java.awt.Color(3, 28, 54));
        Services.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Services.setForeground(new java.awt.Color(255, 255, 255));
        Services.setText("Patient Services");
        Services.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServicesActionPerformed(evt);
            }
        });

        Logout.setBackground(new java.awt.Color(3, 28, 54));
        Logout.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        Hope_Label.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        Hope_Label.setForeground(new java.awt.Color(255, 255, 255));
        Hope_Label.setText("HopeHospital");

        AboutUs.setBackground(new java.awt.Color(3, 28, 54));
        AboutUs.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        AboutUs.setForeground(new java.awt.Color(255, 255, 255));
        AboutUs.setText("About Us");
        AboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutUsActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/hop1.png"))); // NOI18N

        ContactUs.setBackground(new java.awt.Color(3, 28, 54));
        ContactUs.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ContactUs.setForeground(new java.awt.Color(255, 255, 255));
        ContactUs.setText("View Doctors");
        ContactUs.setActionCommand("View Docotors");
        ContactUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactUsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Hope_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(AboutUs)
                .addGap(18, 18, 18)
                .addComponent(Doctors)
                .addGap(18, 18, 18)
                .addComponent(Services)
                .addGap(18, 18, 18)
                .addComponent(ContactUs)
                .addGap(217, 217, 217)
                .addComponent(Logout)
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Doctors)
                            .addComponent(Services)
                            .addComponent(AboutUs)
                            .addComponent(ContactUs)
                            .addComponent(Logout)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Hope_Label)
                            .addComponent(jLabel2))))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1300, 56);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("We specialize in");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(500, 240, 250, 43);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 90)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(3, 28, 54));
        jLabel3.setText("YOU");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(520, 280, 220, 105);

        jPanel3.setBackground(new java.awt.Color(243, 242, 237));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("How can we support you today?");

        serv.setBackground(new java.awt.Color(3, 28, 54));
        serv.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        serv.setForeground(new java.awt.Color(255, 255, 255));
        serv.setText("Check Our Services");
        serv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servActionPerformed(evt);
            }
        });

        book.setBackground(new java.awt.Color(3, 28, 54));
        book.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        book.setForeground(new java.awt.Color(255, 255, 255));
        book.setText("Book Appointment");
        book.setToolTipText("");
        book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookActionPerformed(evt);
            }
        });

        contactbtn.setBackground(new java.awt.Color(3, 28, 54));
        contactbtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        contactbtn.setForeground(new java.awt.Color(255, 255, 255));
        contactbtn.setText("Contact Us");
        contactbtn.setToolTipText("");
        contactbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(serv)
                .addGap(56, 56, 56)
                .addComponent(contactbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(book)
                .addGap(54, 54, 54))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(176, 176, 176))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serv)
                    .addComponent(contactbtn)
                    .addComponent(book))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(280, 460, 690, 151);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/drm.png"))); // NOI18N
        jLabel16.setPreferredSize(new java.awt.Dimension(154, 210));
        jLabel16.setRequestFocusEnabled(false);
        jPanel1.add(jLabel16);
        jLabel16.setBounds(280, 210, 167, 210);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/drc1.png"))); // NOI18N
        jLabel12.setPreferredSize(new java.awt.Dimension(154, 210));
        jLabel12.setRequestFocusEnabled(false);
        jPanel1.add(jLabel12);
        jLabel12.setBounds(800, 210, 167, 210);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/drd.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(90, 210, 154, 210);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/dro1.png"))); // NOI18N
        jLabel8.setPreferredSize(new java.awt.Dimension(154, 210));
        jLabel8.setRequestFocusEnabled(false);
        jPanel1.add(jLabel8);
        jLabel8.setBounds(1030, 210, 167, 210);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(3, 28, 54));
        jLabel6.setText("Your Health, Our Priority");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(510, 120, 260, 29);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 34)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(3, 28, 54));
        jLabel7.setText("Welcome to Hope Hospital");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(440, 70, 400, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutUsActionPerformed
        // TODO add your handling code here:
         About AboutFrame = new About();
         AboutFrame.setVisible(true);
         AboutFrame.pack();// This adjusts the frame size based on its components
         AboutFrame.setLocationRelativeTo(null); // Centers the frame on the screen
    }//GEN-LAST:event_AboutUsActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
       // Show a friendly confirmation message to the patient
    javax.swing.JOptionPane.showMessageDialog(null, 
        "Visit us again. Take care of yourself!", 
        "Logout", 
        javax.swing.JOptionPane.INFORMATION_MESSAGE);

    // Open the Login frame
    Login LoginFrame = new Login();
    LoginFrame.setVisible(true);
    LoginFrame.pack(); // Adjusts the frame size based on its components
    LoginFrame.setLocationRelativeTo(null); // Centers the frame on the screen

    // Close the current frame
    this.dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    private void ServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServicesActionPerformed
         Services ServicesFrame = new Services();
         ServicesFrame.setVisible(true);
         ServicesFrame.pack();// This adjusts the frame size based on its components
         ServicesFrame.setLocationRelativeTo(null); // Centers the frame on the screen
    }//GEN-LAST:event_ServicesActionPerformed

    private void DoctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorsActionPerformed
        // TODO add your handling code here:
        Doctors DoctorsFrame = new Doctors();
         DoctorsFrame.setVisible(true);
         DoctorsFrame.pack();// This adjusts the frame size based on its components
         DoctorsFrame.setLocationRelativeTo(null); // Centers the frame on the screen
    }//GEN-LAST:event_DoctorsActionPerformed

    private void ContactUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactUsActionPerformed
           // TODO add your handling code here:
        Admin ViewFrame = new Admin();
        ViewFrame.setVisible(true);
        ViewFrame.pack();// This adjusts the frame size based on its components
        ViewFrame.setLocationRelativeTo(null); // Centers the frame on the screen

    }//GEN-LAST:event_ContactUsActionPerformed

    private void bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookActionPerformed
      
        // TODO add your handling code here:
        Book BookFrame = new Book();
         BookFrame.setVisible(true);
         BookFrame.pack();// This adjusts the frame size based on its components
         BookFrame.setLocationRelativeTo(null); // Centers the frame on the screen
    }//GEN-LAST:event_bookActionPerformed

    private void servActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servActionPerformed
        // TODO add your handling code here:
        
         Services ServicesFrame = new Services();
         ServicesFrame.setVisible(true);
         ServicesFrame.pack();// This adjusts the frame size based on its components
         ServicesFrame.setLocationRelativeTo(null); // Centers the frame on the screen
    }//GEN-LAST:event_servActionPerformed

    private void contactbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactbtnActionPerformed
        // TODO add your handling code here:
        Contact ContactFrame = new Contact();
         ContactFrame.setVisible(true);
         ContactFrame.pack();// This adjusts the frame size based on its components
         ContactFrame.setLocationRelativeTo(null); // Centers the frame on the screen
    }//GEN-LAST:event_contactbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutUs;
    private javax.swing.JButton ContactUs;
    private javax.swing.JButton Doctors;
    private javax.swing.JLabel Hope_Label;
    private javax.swing.JButton Logout;
    private javax.swing.JButton Services;
    private javax.swing.JButton book;
    private javax.swing.JButton contactbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton serv;
    // End of variables declaration//GEN-END:variables
}
