/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop_project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author AMAL
 */
public class SignUp extends javax.swing.JFrame 
{

    /**
     * Creates new form SignUp
     */
    Connection con=null;
    
    public SignUp() 
    {
        initComponents();
             
        try 
        {
    
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hope?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC" , 
            "root", "1234");
        }
        catch ( SQLException sqlException ) 
        {
            System.out.println(sqlException.getMessage() );
        }

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Right = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        HospitalName = new javax.swing.JLabel();
        Hospital = new javax.swing.JLabel();
        Left = new javax.swing.JPanel();
        SignUp = new javax.swing.JLabel();
        FullName = new javax.swing.JLabel();
        FULLNAME = new javax.swing.JTextField();
        UserName = new javax.swing.JLabel();
        USERNAME = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        PASS = new javax.swing.JPasswordField();
        SignUp_btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Login_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 750));
        jPanel1.setLayout(null);

        Right.setBackground(new java.awt.Color(3, 28, 54));
        Right.setPreferredSize(new java.awt.Dimension(650, 750));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Hospital.png"))); // NOI18N

        HospitalName.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        HospitalName.setForeground(new java.awt.Color(255, 255, 255));
        HospitalName.setText("Hope Hospital");

        Hospital.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        Hospital.setForeground(new java.awt.Color(255, 255, 255));
        Hospital.setText("Your Health, Our Priority");

        javax.swing.GroupLayout RightLayout = new javax.swing.GroupLayout(Right);
        Right.setLayout(RightLayout);
        RightLayout.setHorizontalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightLayout.createSequentialGroup()
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RightLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(Logo))
                    .addGroup(RightLayout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(Hospital))
                    .addGroup(RightLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(HospitalName)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        RightLayout.setVerticalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(HospitalName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Hospital)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        jPanel1.add(Right);
        Right.setBounds(0, 0, 650, 750);

        Left.setBackground(new java.awt.Color(255, 255, 255));
        Left.setPreferredSize(new java.awt.Dimension(650, 750));

        SignUp.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        SignUp.setForeground(new java.awt.Color(3, 28, 54));
        SignUp.setText("Sign Up");

        FullName.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        FullName.setText("Full Name");

        FULLNAME.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        FULLNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FULLNAMEActionPerformed(evt);
            }
        });

        UserName.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        UserName.setText("UserName");

        USERNAME.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        USERNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USERNAMEActionPerformed(evt);
            }
        });

        Password.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        Password.setText("Password");

        PASS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PASSActionPerformed(evt);
            }
        });

        SignUp_btn.setBackground(new java.awt.Color(3, 28, 54));
        SignUp_btn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        SignUp_btn.setForeground(new java.awt.Color(255, 255, 255));
        SignUp_btn.setLabel("Sign Up");
        SignUp_btn.setPreferredSize(new java.awt.Dimension(72, 28));
        SignUp_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUp_btnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(3, 28, 54));
        jLabel5.setText("You have an account");

        Login_btn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Login_btn.setForeground(new java.awt.Color(204, 0, 102));
        Login_btn.setText("Login");
        Login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LeftLayout = new javax.swing.GroupLayout(Left);
        Left.setLayout(LeftLayout);
        LeftLayout.setHorizontalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftLayout.createSequentialGroup()
                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LeftLayout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(SignUp))
                    .addGroup(LeftLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FullName)
                            .addComponent(FULLNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UserName)
                            .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(PASS)
                                .addComponent(USERNAME, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
                            .addComponent(SignUp_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Password)
                            .addGroup(LeftLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Login_btn)))))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        LeftLayout.setVerticalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(SignUp)
                .addGap(42, 42, 42)
                .addComponent(FullName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FULLNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(UserName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(USERNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(Password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PASS, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(SignUp_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Login_btn)
                    .addComponent(jLabel5))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        jPanel1.add(Left);
        Left.setBounds(650, 0, 650, 750);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FULLNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FULLNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FULLNAMEActionPerformed

    private void USERNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USERNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_USERNAMEActionPerformed

    private void PASSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PASSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PASSActionPerformed

    private void SignUp_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUp_btnActionPerformed
 // Get user inputs
    String fname = FULLNAME.getText().trim();
    String username = USERNAME.getText().trim();
    String pass = new String(PASS.getPassword()).trim();

    // Check for empty fields
    if (fname.isEmpty() || username.isEmpty() || pass.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields.", "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Check if the username already exists in the database
    String checkQuery = "SELECT * FROM users WHERE username = ?";
    try (PreparedStatement checkStmt = con.prepareStatement(checkQuery)) {
        checkStmt.setString(1, username);
        ResultSet rs = checkStmt.executeQuery();
        
        if (rs.next()) { // Username already exists
            javax.swing.JOptionPane.showMessageDialog(this, "Username already exists. Please choose another.", "Duplicate Username", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
    } catch (SQLException e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Database error while checking username.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Insert new user into the database
    String insertQuery = "INSERT INTO users (fname, username, pass) VALUES (?, ?, ?)";
    try (PreparedStatement insertStmt = con.prepareStatement(insertQuery)) {
        insertStmt.setString(1, fname);
        insertStmt.setString(2, username);
        insertStmt.setString(3, pass);

        int rowsInserted = insertStmt.executeUpdate();
        if (rowsInserted > 0) {
            // Retrieve the last inserted user_id using LAST_INSERT_ID()
            String lastInsertIdQuery = "SELECT LAST_INSERT_ID()";
            try (PreparedStatement lastIdStmt = con.prepareStatement(lastInsertIdQuery);
                 ResultSet rs = lastIdStmt.executeQuery()) {
                if (rs.next()) {
                    int userId = rs.getInt(1); // Get the last inserted ID
                    System.out.println("New user ID: " + userId); // Optionally, print the user ID for debugging
                    
                    // Use the userId as needed in your app (e.g., for associating appointments)
                }
            }

            javax.swing.JOptionPane.showMessageDialog(this, "Sign Up Successful!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            // Navigate to homepage after successful signup
            HomePage HomeFrame = new HomePage();
            HomeFrame.setVisible(true);
            HomeFrame.pack();
            HomeFrame.setLocationRelativeTo(null);
            this.dispose();
        }
    } catch (SQLException e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Error during sign up. Please try again.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
       
    }//GEN-LAST:event_SignUp_btnActionPerformed

    private void Login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_btnActionPerformed

        Login LoginFrame = new Login();
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setLocationRelativeTo(null);
        this.dispose();

    }//GEN-LAST:event_Login_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FULLNAME;
    private javax.swing.JLabel FullName;
    private javax.swing.JLabel Hospital;
    private javax.swing.JLabel HospitalName;
    private javax.swing.JPanel Left;
    private javax.swing.JButton Login_btn;
    private javax.swing.JLabel Logo;
    private javax.swing.JPasswordField PASS;
    private javax.swing.JLabel Password;
    private javax.swing.JPanel Right;
    private javax.swing.JLabel SignUp;
    private javax.swing.JButton SignUp_btn;
    private javax.swing.JTextField USERNAME;
    private javax.swing.JLabel UserName;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
